# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatFunctionality' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatFunctionality

  target 'ChatFunctionalityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatFunctionalityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase'
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Auth’

  pod ‘FBSDKCoreKit’
  pod ‘FBSDKShareKit’
  pod ‘FBSDKLoginKit’
end
