# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Combined-Maps-ARKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Combined-Maps-ARKit
  pod 'ARCL'

  pod 'Firebase'
  pod ‘Firebase/Database’
  pod ‘Firebase/Storage’
  pod ‘Firebase/Auth’

  pod ‘FBSDKCoreKit’
  pod ‘FBSDKShareKit’
  pod ‘FBSDKLoginKit’

  pod ‘JSQMessagesViewController’

end
